apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "hello-world.fullname" . }}
  labels: 
    app: {{ .Chart.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      serviceAccountName: {{ .Values.serviceAccount }}
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy}}
        env:
        - name: BUCKET_NAME
          value: {{ .Values.bucket.name | quote }}
        - name: QUEUE_NAME
          value: {{ .Values.queue.name | quote }}
        {{- if .Values.account }}
        - name: SERVICE_ACCOUNT
          value: {{ .Values.account.serviceAccountName | quote }}
        {{- end }}
        {{- if .Values.namespace }}
        - name: NAMESPACE
          value: {{ .Values.namespace.namespace | quote }}
        {{- end }}
        ports:
        - containerPort: 3000
