name: Delete Ephemeral Environment

on:
  pull_request:
    types: [closed]

jobs:
  delete-ephemeral-env:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Delete environment
        uses: docker://ghcr.io/humanitec/hctl:latest
        with:
          args: delete environment ${{ github.event.repository.name }} ephemeral-pr-${{ github.event.pull_request.number }}
        env:
          HUMANITEC_AUTH_TOKEN: ${{ secrets.CANYON_DEMO_CANYON_AUTH_TOKEN_PROD }}
          HUMANITEC_ORG: ${{ secrets.CANYON_DEMO_CANYON_ORG }}